### ISSUE TITLE
Queries

### ISSUE THREAD

**Issue by shatgupt** [insidesherpa/shiptivitas-2#3]
In the README, it says `curl -X PUT http://localhost:3001/api/v1/clients/1 -H "Content-Type: application/json" -d '{"status":"in-progress"}'` should do nothing. Why?

Does it mean that marking a client `in-progress` requires a priority compulsorily and the request should return 400 if not provided?

**Comment by julius-is** [comment]
The wording is probably not clear enough.
> Should do nothing
because the status of card id 1 is already **in-progress**. It should not reorder the priority due to the `priority` query is not provided

**Comment by shatgupt** [comment]
Got it. Thanks for the clarification.

**Comment by shatgupt** [comment]
I have a different question and since this issue open, I putting it here.

#### What is the expected result of the following request in README?
`curl -X PUT http://localhost:3001/api/v1/clients/1 -H "Content-Type: application/json" -d '{"status":"in-progress", "priority": 6}'`
It is trying to reorder `in-progress` client 1 from priority 1 to 6. But priority 6 doesn't exist and 5 is the lowest priority for `in-progress` status. Following are my interpretations for the result:

1. The request is invalid and it should have specified priority 5 if it wanted the client to become lowest priority `in-progress` client.
2. Move the client to priority 6 and increase priorities of all clients which are now above it. This creates a gap with no client with priority 5 - priorities are now in the range 1-4 for others and 6 for current client.
3. Just move the client to priority 6 and do nothing else. In this case the priorities will now be from 2 to 6 which I think is not right since it is mentioned that priorities should be from 1 to x.

Which of the above is the expected result?

**Comment by julius-is** [comment]
I am thinking of a more forgiving solution. The logic of calculating whether it should be priority 5 instead of 6 because we are pulling 1 card out of the 'in-progress' swimlane should be done on the back end.
To answer your question, there is a 4th possible implementation:
4. Move the client to the **last** priority on that swimlane and update all cards in that swimlane to remove gaps.

Of course you can also go with solution 2.

**Comment by shatgupt** [comment]
Right. Instead of erroring out, we can assume they meant last priority and go as usual. Just to clarify, (4) wrt to the query above would mean move client to 6 and then update all cards so that priorities are now back in the range 1-5. Am I right?

**Comment by julius-is** [comment]
Yes, that is correct

**Comment by shatgupt** [comment]
Thanks for the clarification.
